spring.application.name=62RosasTattoo
server.port=8080

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.datasource.url=jdbc:mariadb://localhost:3306/rosas-tattoo-v2
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

server.error.include-message=always
server.error.include-binding-errors=always